server:
  port: 8766

com:
  ejlchina:
    searcher:
      implement:
        DefaultSqlExecutor: DEBUG

spring:
  redis:
    # host: 192.168.1.70
    host: 192.168.1.70
    port: 6379
    password: 123456
    timeout: 10000
    database: 0
    maxTotal: 30
    maxIdle: 10
    numTestsPerEvictionRun: 1024
    timeBetweenEvictionRunsMillis: 30000
    minEvictableIdleTimeMillis: 1800000
    softMinEvictableIdleTimeMillis: 10000
    # 连接池最大阻塞等待时间（使用负值表示没有限制）
    maxWaitMillis: 1500
    testOnBorrow: true
    testWhileIdle: true
    blockWhenExhausted: false
    JmxEnabled: true

  datasource:
      driverClassName: com.mysql.cj.jdbc.Driver

      # 主库数据源
      url: jdbc:mysql://192.168.1.70:3306/carbonstop-auth-manage?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
      #url: jdbc:mysql://rm-2ze1te416biito3vg.mysql.rds.aliyuncs.com/carbonstop_operation?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
      #                url: jdbc:mysql://47.94.198.85:3306/carbonstop_operation?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
      #                username: root
      #                password: xfz3306
      #username: base_operation_rw
      #password: 1AvhFZoWCiryynvm
      username: root
      password: 123456
      # 从库数据源
#datasource:
#  url: jdbc:postgresql://192.168.1.84:5432/supervison_platform
#  username: supervison
#  password: 123
#  driver-class-name: org.postgresql.Driver
#  #解决整合后报的一个错：<aused by: java.sql.SQLFeatureNotSupportedException: 这个 org.postgresql.jdbc.PgConnection.createClob() 方法尚未被实作。>
#  jpa:
#    properties:
#      hibernate:
#        jdbc:
#          lob:
#            non_contextual_creation: true

mybatis-plus:
  global-config:
    db-config:
      table-prefix: platform.
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.mybatisPlus
  configuration:
    map-underscore-to-camel-case: true

    # redis 配置
  #    redis:
  #      # 地址
  #      #        host: 47.94.198.85
  #      host: 192.168.1.70
  #      # 端口，默认为6379
  #      port: 6379
  #      # 数据库索引
  #      database: 1
  #      #password: base_be_rw:PC1n@nr9m3NwkyLV
  #      #        password: xfz6379
  #      password: 123456
  #      # 连接超时时间
  #      timeout: 10s
  #      lettuce:
  #        pool:
  #          # 连接池中的最小空闲连接
  #          min-idle: 0
  #          # 连接池中的最大空闲连接
  #          max-idle: 8
  #          # 连接池的最大数据库连接数
  #          max-active: 8
  #          # #连接池最大阻塞等待时间（使用负值表示没有限制）
  #          max-wait: -1ms

  application:
    name: spring-boot-neo4j
  profiles:
    # 环境配置
    active: dev

  data:
    neo4j: # neo4j配置
      uri: bolt://localhost:7474
      username: neo4j
      password: root
  redis:
    database: 4
    host: 192.168.61.50
    port: 6379
    timeout: 5000
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1

elasticsearch:
  ip: 192.168.61.45,192.168.61.44,192.168.61.46
  port: 9200
  pool: 5
  name: elasticsearch